import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client'
import Link from 'next/link'

export default function Home({ sell }) {
  console.log("Sell", sell)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          {sell.map(key => {
            return (
              <Link href={'/cars-for-sale/' + key.make} key={key.vehicle_key} passHref>
                <div className={styles.card}>
                  <img src={key.main_image} alt="carImage" style={{ width: "16rem" }} />
                  <h3>{key.year} {key.make} {key.model}</h3>
                  <p>{key.price_drive_away}</p>
                  <ul>
                    <li>
                      {key.transmission}
                    </li>
                    <li>
                      {key.odometer}
                    </li>
                    <li>
                      {key.colour}
                    </li>
                    <li>
                      {key.seat_capacity}
                    </li>
                  </ul>
                </div>
              </Link>
            )
          })}

        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({

    uri: 'https://dev-carsforsale.drivemustang.com.au/graphql',
    cache: new InMemoryCache()
  })

  const { data } = await client.query({
    query: gql`{
      DealerListings {
        results {
          year
          main_image
          make
          model
          price_drive_away
          vehicle_key
          odometer
          transmission
          colour
          seat_capacity
          location_state
        }
      }
    }`


  })
  console.log(data);
  return {
    props: {
      sell: data.DealerListings.results
    }
  }
}
